# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16e2647564580a562726eecc6e99e9c2"
name = "detailForm"
handle = "detailform-1"
application_url = "https://thus-practice-britannica-limiting.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://thus-practice-britannica-limiting.trycloudflare.com/auth/callback",
  "https://thus-practice-britannica-limiting.trycloudflare.com/auth/shopify/callback",
  "https://thus-practice-britannica-limiting.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
